openapi: 3.0.0
info:
  title: Product API
  description: API for managing and retrieving product details in the shopping application.
  version: 1.0.0
servers:
  - url: https://api.yourshoppingapp.com/products
    description: Product API Server
paths:
  /:
    get:
      summary: List all products
      description: Retrieve a list of all available products.
      x-eventcatalog-message-type: query
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /{productId}:
    get:
      summary: Get a product by ID
      description: Retrieve details of a specific product by its ID.
      x-eventcatalog-message-type: query
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A single product
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
        '404':
          description: Product not found

  /categories:
    get:
      summary: List all product categories
      description: Retrieve a list of all product categories.
      x-eventcatalog-message-type: query
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'

  /categories/{categoryId}:
    get:
      summary: Get products by category
      description: Retrieve a list of products within a specific category.
      x-eventcatalog-message-type: query
      parameters:
        - name: categoryId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of products in the category
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /{productId}/reviews:
    get:
      summary: Get reviews for a product
      description: Retrieve a list of reviews for a specific product.
      x-eventcatalog-message-type: query
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of reviews for the product
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'

    post:
      summary: Submit a review for a product
      description: Submit a new review for a product.
      x-eventcatalog-message-type: command
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        description: The review to submit
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Review'
      responses:
        '201':
          description: Review submitted

  /{productId}/reviews/{reviewId}:
    get:
      summary: Get a specific review by ID
      description: Retrieve a specific review for a product by its review ID.
      x-eventcatalog-message-type: query
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
        - name: reviewId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: The review details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'

    delete:
      summary: Delete a review by ID
      description: Delete a specific review for a product.
      x-eventcatalog-message-type: command
      parameters:
        - name: productId
          in: path
          required: true
          schema:
            type: string
        - name: reviewId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Review deleted successfully

components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
          format: float
        category:
          type: string
        imageUrl:
          type: string
      required:
        - id
        - name
        - price
        - category

    Category:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      required:
        - id
        - name

    Review:
      type: object
      properties:
        id:
          type: string
        productId:
          type: string
        rating:
          type: integer
          minimum: 1
          maximum: 5
        comment:
          type: string
      required:
        - id
        - productId
        - rating
